language: java
jdk:
 - openjdk11
matrix:
  fast_finish: true
  include:
    - jdk: openjdk11
      env:
        - DESC="build with OpenJDK11"
        - CMD="mvn -e package -Passembly && mvn -e site -Dlinkcheck.skip=true"
branches:
  only:
  - master
deploy:
 provider: heroku
 api-key: 
  secure: $HEROKU_API_KEY
 app: lollito-fm

