language: java
jdk:
 - openjdk11
branches:
  only:
  - master
before_install:
 - pip install --user codecov
after_success:
 - codecov
deploy:
 provider: heroku
 api-key: 
  secure: $HEROKU_API_KEY
 app: lollito-fm

