language: java
jdk:
 - openjdk11
install: true
script: mvn clean package -DskipTests=true
branches:
  only:
  - master
deploy:
 provider: heroku
 api-key: 
  secure: $HEROKU_API_KEY
 app: lollito-fm

